// ============================================================
// CAMPUS CONNECT AI - College Data Constants
// Sri Satya Institute of Engineering and Technology
// ============================================================

export const COLLEGE_INFO = {
  name: "Sri Satya Institute of Engineering and Technology",
  shortName: "SSIET",
  tagline: "Empowering Future Engineers Through Innovation, Technology and Excellence",
  description:
    "Sri Satya Institute of Engineering and Technology is a premier engineering institution dedicated to nurturing talent, fostering innovation, and preparing students for the challenges of a technology-driven world. With state-of-the-art facilities and industry-aligned curriculum, we shape the engineers of tomorrow.",
  established: 2000,
  location: "Andhra Pradesh, India",
  phone: "+91 9000-000-000",
  email: "info@ssiet.ac.in",
  website: "www.ssiet.ac.in",
  address: "Sri Satya Nagar, Narsapur Road, West Godavari, Andhra Pradesh - 534001",
  vision:
    "To be a globally recognized institution of excellence in engineering education, research, and innovation, producing competent professionals with strong ethical values.",
  mission: [
    "Provide quality technical education with industry-aligned curriculum",
    "Foster a culture of research, innovation, and entrepreneurship",
    "Develop professionally competent and socially responsible engineers",
    "Build strong industry-academia partnerships for real-world learning",
    "Promote ethical values, leadership skills, and holistic development",
  ],
  socialMedia: {
    linkedin: "#",
    twitter: "#",
    facebook: "#",
    instagram: "#",
    youtube: "#",
  },
} as const;

export const COLLEGE_STATS = [
  { label: "Years of Excellence", value: 25, suffix: "+", icon: "Award" },
  { label: "Students Enrolled", value: 5000, suffix: "+", icon: "Users" },
  { label: "Faculty Members", value: 150, suffix: "+", icon: "GraduationCap" },
  { label: "Engineering Programs", value: 8, suffix: "", icon: "BookOpen" },
  { label: "Placement Rate", value: 92, suffix: "%", icon: "TrendingUp" },
] as const;

export const COLLEGE_TIMELINE = [
  {
    year: 2000,
    title: "College Establishment",
    description:
      "Sri Satya Institute of Engineering and Technology was founded with a vision to provide quality engineering education in Andhra Pradesh.",
  },
  {
    year: 2004,
    title: "Infrastructure Expansion",
    description:
      "Major campus expansion with new academic blocks, advanced laboratories, and enhanced student facilities.",
  },
  {
    year: 2008,
    title: "New Engineering Departments",
    description:
      "Launch of specialized programs in Electronics, Mechanical, and Civil Engineering to meet growing industry demands.",
  },
  {
    year: 2012,
    title: "Industry Collaborations",
    description:
      "Forged strategic partnerships with leading IT companies and manufacturing firms for placement and internship programs.",
  },
  {
    year: 2016,
    title: "AI & Innovation Hub",
    description:
      "Established a cutting-edge AI and Data Science lab, and launched the Innovation and Entrepreneurship Development Cell.",
  },
  {
    year: 2020,
    title: "Digital Transformation",
    description:
      "Complete digitalization of campus infrastructure with smart classrooms, high-speed internet, and online learning platforms.",
  },
  {
    year: 2024,
    title: "Centre of Excellence",
    description:
      "Recognized as a Centre of Excellence in Engineering Education with NAAC accreditation and NBA certifications.",
  },
] as const;

export const ACHIEVEMENTS = [
  {
    category: "Academic",
    icon: "Trophy",
    title: "NAAC Accredited Institution",
    description:
      "Accredited by the National Assessment and Accreditation Council with a high-grade score for academic excellence.",
  },
  {
    category: "Student",
    icon: "Medal",
    title: "State Toppers",
    description:
      "Consistently producing university rank holders and state board toppers across all engineering programs.",
  },
  {
    category: "Research",
    icon: "Microscope",
    title: "50+ Research Publications",
    description:
      "Faculty and students have published over 50 research papers in national and international journals.",
  },
  {
    category: "Industry",
    icon: "Building2",
    title: "100+ Industry Partners",
    description:
      "Strong network of over 100 industry partners providing internship and placement opportunities.",
  },
] as const;

export const DEPARTMENTS = [
  {
    id: "cse",
    name: "Computer Science Engineering",
    shortName: "CSE",
    slug: "computer-science-engineering",
    icon: "Code2",
    color: "emerald",
    description:
      "The CSE department offers a comprehensive curriculum covering algorithms, data structures, operating systems, networks, and modern software development practices.",
    hod: "Dr. Ramesh Kumar",
    hodQualification: "Ph.D, M.Tech (IIT Madras)",
    facultyCount: 25,
    intake: 120,
    established: 2000,
    labs: [
      "Programming Lab",
      "Data Structures Lab",
      "Networks Lab",
      "Database Lab",
      "Project Lab",
    ],
    majorSubjects: [
      "Data Structures & Algorithms",
      "Database Management Systems",
      "Operating Systems",
      "Computer Networks",
      "Software Engineering",
      "Web Technologies",
      "Machine Learning",
      "Cloud Computing",
    ],
    careerOpportunities: [
      "Software Engineer",
      "Web Developer",
      "Database Administrator",
      "System Analyst",
      "DevOps Engineer",
      "IT Consultant",
    ],
    researchAreas: [
      "Machine Learning",
      "Cybersecurity",
      "Cloud Computing",
      "IoT",
    ],
  },
  {
    id: "aids",
    name: "Artificial Intelligence and Data Science",
    shortName: "AI&DS",
    slug: "artificial-intelligence-data-science",
    icon: "Brain",
    color: "gold",
    description:
      "A future-focused department dedicated to the science of intelligent systems, big data analytics, and machine learning technologies that power the modern world.",
    hod: "Dr. Priya Sharma",
    hodQualification: "Ph.D (AI), M.Tech (NIT)",
    facultyCount: 18,
    intake: 60,
    established: 2018,
    labs: [
      "AI Research Lab",
      "Data Analytics Lab",
      "Deep Learning Lab",
      "NLP Lab",
    ],
    majorSubjects: [
      "Machine Learning",
      "Deep Learning",
      "Natural Language Processing",
      "Computer Vision",
      "Big Data Analytics",
      "Python Programming",
      "Statistics & Probability",
      "Data Visualization",
    ],
    careerOpportunities: [
      "AI Engineer",
      "Data Scientist",
      "ML Engineer",
      "Research Scientist",
      "Business Analyst",
      "Data Analyst",
    ],
    researchAreas: [
      "Deep Learning",
      "NLP",
      "Computer Vision",
      "Predictive Analytics",
    ],
  },
  {
    id: "ece",
    name: "Electronics and Communication Engineering",
    shortName: "ECE",
    slug: "electronics-communication-engineering",
    icon: "Cpu",
    color: "navy",
    description:
      "The ECE department trains students in the design of electronic circuits, communication systems, signal processing, and embedded technologies.",
    hod: "Dr. Vijay Rao",
    hodQualification: "Ph.D, M.Tech (BITS Pilani)",
    facultyCount: 22,
    intake: 60,
    established: 2000,
    labs: [
      "Electronics Lab",
      "Communication Lab",
      "VLSI Lab",
      "Microprocessor Lab",
      "Signal Processing Lab",
    ],
    majorSubjects: [
      "Analog Electronics",
      "Digital Electronics",
      "Communication Systems",
      "VLSI Design",
      "Signal Processing",
      "Embedded Systems",
      "Microprocessors",
      "Wireless Communication",
    ],
    careerOpportunities: [
      "Electronics Engineer",
      "Telecom Engineer",
      "VLSI Designer",
      "Embedded Systems Developer",
      "RF Engineer",
      "Hardware Engineer",
    ],
    researchAreas: [
      "VLSI Design",
      "IoT",
      "5G Communications",
      "Signal Processing",
    ],
  },
  {
    id: "mech",
    name: "Mechanical Engineering",
    shortName: "MECH",
    slug: "mechanical-engineering",
    icon: "Settings",
    color: "orange",
    description:
      "A classical yet evolving engineering discipline that covers thermodynamics, manufacturing, CAD/CAM, robotics, and sustainable energy systems.",
    hod: "Dr. Srinivas Rao",
    hodQualification: "Ph.D, M.Tech (JNTU)",
    facultyCount: 20,
    intake: 60,
    established: 2000,
    labs: [
      "Workshop",
      "CAD/CAM Lab",
      "Fluid Mechanics Lab",
      "Heat Transfer Lab",
      "Metrology Lab",
    ],
    majorSubjects: [
      "Engineering Mechanics",
      "Thermodynamics",
      "Manufacturing Technology",
      "CAD/CAM",
      "Fluid Mechanics",
      "Robotics",
      "Heat Transfer",
      "Machine Design",
    ],
    careerOpportunities: [
      "Mechanical Engineer",
      "Design Engineer",
      "Production Manager",
      "Automation Engineer",
      "Quality Engineer",
      "R&D Engineer",
    ],
    researchAreas: [
      "Robotics",
      "Renewable Energy",
      "Smart Manufacturing",
      "Composite Materials",
    ],
  },
  {
    id: "civil",
    name: "Civil Engineering",
    shortName: "CIVIL",
    slug: "civil-engineering",
    icon: "Building",
    color: "amber",
    description:
      "Civil Engineering at SSIET focuses on structural analysis, transportation, geotechnical engineering, environmental studies, and sustainable infrastructure development.",
    hod: "Dr. Lakshmi Devi",
    hodQualification: "Ph.D, M.Tech (Osmania University)",
    facultyCount: 18,
    intake: 60,
    established: 2000,
    labs: [
      "Structures Lab",
      "Geotechnical Lab",
      "Fluid Mechanics Lab",
      "Survey Lab",
      "Environmental Lab",
    ],
    majorSubjects: [
      "Structural Analysis",
      "Geotechnical Engineering",
      "Environmental Engineering",
      "Transportation Engineering",
      "Surveying",
      "Construction Management",
      "Water Resources",
      "Remote Sensing & GIS",
    ],
    careerOpportunities: [
      "Structural Engineer",
      "Site Engineer",
      "Urban Planner",
      "Environmental Engineer",
      "Project Manager",
      "Government Services",
    ],
    researchAreas: [
      "Green Buildings",
      "Smart Cities",
      "Geotechnics",
      "Water Management",
    ],
  },
] as const;

export const COURSES = [
  {
    id: "b-tech-cse",
    name: "B.Tech Computer Science Engineering",
    department: "cse",
    departmentName: "Computer Science Engineering",
    slug: "computer-science-engineering",
    duration: "4 Years",
    intake: 120,
    type: "Undergraduate",
    eligibility: [
      "10+2 / Intermediate with Mathematics, Physics & Chemistry",
      "Minimum 60% aggregate in qualifying examination",
      "Valid EAMCET / JEE Rank",
      "Age limit: 17-25 years",
    ],
    description:
      "Bachelor of Technology in Computer Science Engineering is a 4-year undergraduate program covering core computer science fundamentals and cutting-edge technologies. Students gain expertise in software development, algorithms, databases, and modern computing paradigms.",
    curriculum: {
      "Year 1": [
        "Engineering Mathematics I & II",
        "Engineering Physics",
        "Engineering Chemistry",
        "Programming in C",
        "Basic Electrical Engineering",
        "Engineering Drawing",
      ],
      "Year 2": [
        "Data Structures",
        "Object Oriented Programming (Java)",
        "Computer Organization",
        "Discrete Mathematics",
        "Database Management Systems",
        "Software Engineering",
      ],
      "Year 3": [
        "Design & Analysis of Algorithms",
        "Operating Systems",
        "Computer Networks",
        "Web Technologies",
        "Compiler Design",
        "Machine Learning",
      ],
      "Year 4": [
        "Cloud Computing",
        "Cyber Security",
        "AI & Deep Learning",
        "Distributed Systems",
        "Major Project",
        "Industry Internship",
      ],
    },
    careerOpportunities: [
      "Software Engineer",
      "Full Stack Developer",
      "Data Scientist",
      "DevOps Engineer",
      "System Architect",
      "IT Consultant",
    ],
    higherStudies: [
      "M.Tech / MS in Computer Science",
      "MBA in IT Management",
      "Ph.D in Computer Science",
      "Specialized certifications (AWS, Google, Microsoft)",
    ],
    icon: "Code2",
  },
  {
    id: "b-tech-aids",
    name: "B.Tech AI & Data Science",
    department: "aids",
    departmentName: "Artificial Intelligence and Data Science",
    slug: "artificial-intelligence-data-science",
    duration: "4 Years",
    intake: 60,
    type: "Undergraduate",
    eligibility: [
      "10+2 / Intermediate with Mathematics, Physics & Chemistry",
      "Minimum 60% aggregate in qualifying examination",
      "Valid EAMCET / JEE Rank",
      "Age limit: 17-25 years",
    ],
    description:
      "B.Tech in Artificial Intelligence and Data Science is a specialized program designed to meet the growing demand for AI professionals. Students master machine learning, deep learning, data analytics, and intelligent system design.",
    curriculum: {
      "Year 1": [
        "Engineering Mathematics",
        "Statistics & Probability",
        "Python Programming",
        "Data Structures",
        "Linear Algebra",
        "Introduction to AI",
      ],
      "Year 2": [
        "Machine Learning Fundamentals",
        "Database Systems",
        "Data Visualization",
        "Big Data Technologies",
        "Pattern Recognition",
        "Python for Data Science",
      ],
      "Year 3": [
        "Deep Learning",
        "Natural Language Processing",
        "Computer Vision",
        "Cloud Computing for AI",
        "Business Intelligence",
        "AI Ethics",
      ],
      "Year 4": [
        "Generative AI",
        "MLOps & Deployment",
        "Research Methodology",
        "Capstone Project",
        "Industry Internship",
        "Electives",
      ],
    },
    careerOpportunities: [
      "AI Engineer",
      "Data Scientist",
      "ML Engineer",
      "Research Scientist",
      "Business Analyst",
      "AI Product Manager",
    ],
    higherStudies: [
      "M.Tech in AI / Data Science",
      "MS in Machine Learning",
      "Ph.D in AI Research",
      "Industry Certifications (TensorFlow, AWS ML)",
    ],
    icon: "Brain",
  },
  {
    id: "b-tech-ece",
    name: "B.Tech Electronics & Communication",
    department: "ece",
    departmentName: "Electronics and Communication Engineering",
    slug: "electronics-communication-engineering",
    duration: "4 Years",
    intake: 60,
    type: "Undergraduate",
    eligibility: [
      "10+2 / Intermediate with Mathematics, Physics & Chemistry",
      "Minimum 60% aggregate in qualifying examination",
      "Valid EAMCET / JEE Rank",
      "Age limit: 17-25 years",
    ],
    description:
      "B.Tech in Electronics and Communication Engineering provides a strong foundation in electronic circuits, communication systems, signal processing, and VLSI design, preparing students for careers in telecommunications and embedded systems.",
    curriculum: {
      "Year 1": [
        "Engineering Mathematics",
        "Engineering Physics",
        "Basic Electronics",
        "Circuit Theory",
        "Programming in C",
        "Engineering Drawing",
      ],
      "Year 2": [
        "Analog Electronics",
        "Digital Electronics",
        "Signals & Systems",
        "Electromagnetic Theory",
        "Communication Systems",
        "Network Analysis",
      ],
      "Year 3": [
        "VLSI Design",
        "Microprocessors & Microcontrollers",
        "Digital Signal Processing",
        "Wireless Communication",
        "Embedded Systems",
        "Antenna & Wave Propagation",
      ],
      "Year 4": [
        "Advanced Communication",
        "IoT Systems",
        "5G Technologies",
        "Optical Fiber Communication",
        "Major Project",
        "Industry Internship",
      ],
    },
    careerOpportunities: [
      "Electronics Engineer",
      "Telecom Engineer",
      "VLSI Designer",
      "Embedded Developer",
      "RF Engineer",
      "Hardware Engineer",
    ],
    higherStudies: [
      "M.Tech in VLSI / Communication",
      "MS in Electronics",
      "MBA in Technology Management",
      "Ph.D Research",
    ],
    icon: "Cpu",
  },
  {
    id: "b-tech-mech",
    name: "B.Tech Mechanical Engineering",
    department: "mech",
    departmentName: "Mechanical Engineering",
    slug: "mechanical-engineering",
    duration: "4 Years",
    intake: 60,
    type: "Undergraduate",
    eligibility: [
      "10+2 / Intermediate with Mathematics, Physics & Chemistry",
      "Minimum 60% aggregate in qualifying examination",
      "Valid EAMCET / JEE Rank",
      "Age limit: 17-25 years",
    ],
    description:
      "B.Tech in Mechanical Engineering is a comprehensive program covering thermodynamics, fluid mechanics, manufacturing, CAD/CAM, and robotics. Students develop a deep understanding of mechanical systems and their applications in modern industry.",
    curriculum: {
      "Year 1": [
        "Engineering Mathematics",
        "Engineering Physics",
        "Engineering Mechanics",
        "Engineering Drawing",
        "Metallurgy",
        "Basic Manufacturing",
      ],
      "Year 2": [
        "Thermodynamics",
        "Fluid Mechanics",
        "Strength of Materials",
        "Kinematics of Machinery",
        "Manufacturing Processes",
        "Material Science",
      ],
      "Year 3": [
        "CAD/CAM",
        "Heat Transfer",
        "Machine Design",
        "Robotics & Automation",
        "Industrial Engineering",
        "Dynamics of Machinery",
      ],
      "Year 4": [
        "Advanced Manufacturing",
        "Composite Materials",
        "Renewable Energy",
        "FEA & Simulation",
        "Major Project",
        "Industry Internship",
      ],
    },
    careerOpportunities: [
      "Mechanical Engineer",
      "Design Engineer",
      "Production Manager",
      "Quality Engineer",
      "Automation Engineer",
      "R&D Specialist",
    ],
    higherStudies: [
      "M.Tech in Mechanical Engineering",
      "MBA in Operations",
      "MS in Manufacturing",
      "Ph.D Research",
    ],
    icon: "Settings",
  },
  {
    id: "b-tech-civil",
    name: "B.Tech Civil Engineering",
    department: "civil",
    departmentName: "Civil Engineering",
    slug: "civil-engineering",
    duration: "4 Years",
    intake: 60,
    type: "Undergraduate",
    eligibility: [
      "10+2 / Intermediate with Mathematics, Physics & Chemistry",
      "Minimum 60% aggregate in qualifying examination",
      "Valid EAMCET / JEE Rank",
      "Age limit: 17-25 years",
    ],
    description:
      "B.Tech Civil Engineering provides in-depth knowledge of structural design, geotechnical engineering, water resources, environmental engineering, and transportation systems for building sustainable infrastructure.",
    curriculum: {
      "Year 1": [
        "Engineering Mathematics",
        "Engineering Physics",
        "Engineering Chemistry",
        "Engineering Mechanics",
        "Surveying",
        "Building Materials",
      ],
      "Year 2": [
        "Structural Analysis",
        "Fluid Mechanics",
        "Soil Mechanics",
        "Transportation Engineering",
        "Environmental Engineering",
        "Hydraulics",
      ],
      "Year 3": [
        "Design of Concrete Structures",
        "Geotechnical Engineering",
        "Water Resources Engineering",
        "Highway Engineering",
        "Construction Management",
        "Remote Sensing & GIS",
      ],
      "Year 4": [
        "Advanced Structural Design",
        "Smart Infrastructure",
        "Earthquake Engineering",
        "Project Management",
        "Major Project",
        "Industry Internship",
      ],
    },
    careerOpportunities: [
      "Structural Engineer",
      "Site Engineer",
      "Urban Planner",
      "Environmental Engineer",
      "Project Manager",
      "Government Services (APSRTC, PWD)",
    ],
    higherStudies: [
      "M.Tech in Structural / Geotechnical Engineering",
      "MBA in Construction Management",
      "GATE for PSU jobs",
      "Ph.D Research",
    ],
    icon: "Building",
  },
] as const;

export const FEE_STRUCTURE = [
  {
    courseId: "b-tech-cse",
    courseName: "B.Tech Computer Science Engineering",
    department: "CSE",
    academicYear: "2024-25",
    tuitionFee: 85000,
    hostelFee: 55000,
    transportFee: 18000,
    examinationFee: 3000,
    otherCharges: 7000,
    totalFee: 168000,
    scholarshipAvailable: true,
  },
  {
    courseId: "b-tech-aids",
    courseName: "B.Tech AI & Data Science",
    department: "AI&DS",
    academicYear: "2024-25",
    tuitionFee: 90000,
    hostelFee: 55000,
    transportFee: 18000,
    examinationFee: 3000,
    otherCharges: 7000,
    totalFee: 173000,
    scholarshipAvailable: true,
  },
  {
    courseId: "b-tech-ece",
    courseName: "B.Tech Electronics & Communication",
    department: "ECE",
    academicYear: "2024-25",
    tuitionFee: 80000,
    hostelFee: 55000,
    transportFee: 18000,
    examinationFee: 3000,
    otherCharges: 7000,
    totalFee: 163000,
    scholarshipAvailable: true,
  },
  {
    courseId: "b-tech-mech",
    courseName: "B.Tech Mechanical Engineering",
    department: "MECH",
    academicYear: "2024-25",
    tuitionFee: 78000,
    hostelFee: 55000,
    transportFee: 18000,
    examinationFee: 3000,
    otherCharges: 7000,
    totalFee: 161000,
    scholarshipAvailable: true,
  },
  {
    courseId: "b-tech-civil",
    courseName: "B.Tech Civil Engineering",
    department: "CIVIL",
    academicYear: "2024-25",
    tuitionFee: 75000,
    hostelFee: 55000,
    transportFee: 18000,
    examinationFee: 3000,
    otherCharges: 7000,
    totalFee: 158000,
    scholarshipAvailable: true,
  },
] as const;

export const SCHOLARSHIPS = [
  {
    id: "merit-scholarship",
    name: "Merit Excellence Scholarship",
    type: "Merit-Based",
    icon: "Trophy",
    eligibility: [
      "Minimum 90% aggregate in 10+2 qualifying examination",
      "Top EAMCET rankers (within State Rank 5000)",
      "First year students only",
      "No backlog in previous semesters",
    ],
    benefits: [
      "50% tuition fee waiver for all 4 years",
      "Certificate of Excellence",
      "Priority lab access and mentorship",
    ],
    applicationProcess: [
      "Submit merit scholarship application form",
      "Attach 10+2 mark sheets and EAMCET rank card",
      "Personal interview with scholarship committee",
      "Announcement within 30 days of admission",
    ],
    documentsRequired: [
      "10+2 / Intermediate mark sheet",
      "EAMCET Hall Ticket and Rank Card",
      "Income certificate (if applicable)",
      "Passport-size photographs",
      "Aadhar Card copy",
    ],
    deadline: "30th September each year",
  },
  {
    id: "sc-st-scholarship",
    name: "SC/ST Government Scholarship",
    type: "Government",
    icon: "Shield",
    eligibility: [
      "Students belonging to SC/ST communities",
      "Valid caste certificate from competent authority",
      "Annual family income below ₹2.5 Lakhs",
      "Minimum 50% marks in qualifying exam",
    ],
    benefits: [
      "Full tuition fee reimbursement",
      "Hostel fee reimbursement",
      "Book and stationery allowance",
    ],
    applicationProcess: [
      "Apply through official government scholarship portal",
      "Submit documents at college scholarship office",
      "Verification by caste welfare department",
      "Scholarship disbursed directly to student account",
    ],
    documentsRequired: [
      "Caste certificate",
      "Income certificate",
      "Bonafide certificate from college",
      "Bank account details",
      "Aadhar Card",
    ],
    deadline: "31st October each year",
  },
  {
    id: "sports-scholarship",
    name: "Sports Achievement Scholarship",
    type: "Sports",
    icon: "Medal",
    eligibility: [
      "National / State level sports achievement certificate",
      "Active participation in college sports teams",
      "Minimum 60% in academic examinations",
      "Recommended by Physical Education Department",
    ],
    benefits: [
      "25% tuition fee concession",
      "Sports kit and equipment allowance",
      "Special coaching and training support",
    ],
    applicationProcess: [
      "Obtain recommendation from Physical Education Dept.",
      "Submit sports achievement certificates",
      "Appear before Sports Committee",
      "Decision communicated within 15 days",
    ],
    documentsRequired: [
      "Sports achievement certificates",
      "Recommendation letter from PE Department",
      "Identity proof",
      "Academic mark sheets",
    ],
    deadline: "Rolling admissions",
  },
  {
    id: "pwd-scholarship",
    name: "Persons with Disabilities Scholarship",
    type: "Government",
    icon: "Heart",
    eligibility: [
      "Valid disability certificate (minimum 40% disability)",
      "Minimum 50% marks in qualifying examination",
      "Issued by competent medical authority",
    ],
    benefits: [
      "Full tuition fee reimbursement",
      "Accessible infrastructure support",
      "Reader allowance (if applicable)",
    ],
    applicationProcess: [
      "Submit disability certificate and application form",
      "Medical verification by college medical officer",
      "Application forwarded to welfare department",
      "Scholarship credited each semester",
    ],
    documentsRequired: [
      "Disability certificate from CMO/Civil Surgeon",
      "Medical fitness certificate",
      "10+2 mark sheets",
      "Bank passbook copy",
      "Aadhar Card",
    ],
    deadline: "30th November each year",
  },
] as const;

export const PLACEMENT_STATS = {
  highestPackage: "12 LPA",
  averagePackage: "4.5 LPA",
  placementRate: 92,
  companies: 100,
  year: "2023-24",
} as const;

export const RECRUITERS = [
  "TCS", "Infosys", "Wipro", "HCL", "Tech Mahindra",
  "Capgemini", "Accenture", "Cognizant", "IBM", "L&T",
] as const;

export const FACILITIES = [
  {
    name: "Smart Classrooms",
    icon: "Monitor",
    description: "Fully equipped digital classrooms with interactive boards and modern AV systems.",
    image: "/images/smart-classroom.png",
  },
  {
    name: "AI & Research Labs",
    icon: "Brain",
    description: "State-of-the-art AI labs with GPU workstations and cloud computing access.",
    image: "/images/ai-lab.png",
  },
  {
    name: "Central Library",
    icon: "BookOpen",
    description: "A vast collection of 50,000+ books, digital journals, and online resources.",
    image: "/images/library.png",
  },
  {
    name: "Student Hostel",
    icon: "Home",
    description: "Comfortable and secure hostel facilities for both boys and girls.",
    image: "/images/hostel.png",
  },
  {
    name: "Sports Complex",
    icon: "Dumbbell",
    description: "Multi-sport complex with indoor and outdoor facilities for physical fitness.",
    image: "/images/campus/sports-ground.png",
  },
  {
    name: "Cafeteria",
    icon: "UtensilsCrossed",
    description: "Clean, hygienic cafeteria serving nutritious meals at affordable prices.",
    image: "/images/cafeteria.png",
  },
] as const;

export const WHY_CHOOSE_US = [
  {
    icon: "GraduationCap",
    title: "Industry-Focused Education",
    description:
      "Curriculum co-designed with industry experts, ensuring students are job-ready from day one.",
  },
  {
    icon: "Building2",
    title: "Modern Infrastructure",
    description:
      "Over 10 specialized labs, smart classrooms, high-speed Wi-Fi campus, and state-of-the-art facilities.",
  },
  {
    icon: "Users",
    title: "Experienced Faculty",
    description:
      "150+ highly qualified faculty members with PhDs and industry experience from premier institutions.",
  },
  {
    icon: "TrendingUp",
    title: "Career Development",
    description:
      "Dedicated placement cell, regular industry interactions, and 92% placement success rate.",
  },
  {
    icon: "Lightbulb",
    title: "Innovation Culture",
    description:
      "Entrepreneurship cell, hackathons, tech fests, and research opportunities for creative minds.",
  },
  {
    icon: "Globe",
    title: "Holistic Development",
    description:
      "Sports, arts, cultural activities, and leadership programs for all-round student growth.",
  },
] as const;

export const NAV_LINKS = [
  { href: "/", label: "Home" },
  { href: "/about", label: "About" },
  { href: "/campus", label: "Campus Tour" },
  { href: "/courses", label: "Courses" },
  { href: "/departments", label: "Departments" },
  { href: "/admissions", label: "Admissions" },
  { href: "/fees", label: "Fees" },
  { href: "/scholarships", label: "Scholarships" },
  { href: "/student-life", label: "Student Life" },
  { href: "/events", label: "Events" },
  { href: "/placements", label: "Placements" },
  { href: "/internships", label: "Internships" },
  { href: "/alumni", label: "Alumni Network" },
  { href: "/faq", label: "FAQ" },
  { href: "/enquiry", label: "Enquiry" },
  { href: "/contact", label: "Contact" },
] as const;
